version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # Mengunduh dan memasang hadolint secara otomatis
      - run:
          name: Install Hadolint
          command: |
            sudo wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.14.0/hadolint-linux-x86_64
            sudo chmod +x /usr/local/bin/hadolint
      - run:
          name: Run Hadolint against Dockerfile
          command: hadolint Dockerfile

  test-app:
    docker:
      # Menggunakan image Go resmi yang stabil
      - image: cimg/go:1.15
    steps:
      - checkout
      - run:
          name: Run Unit Test
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # Mengaktifkan remote docker daemon agar kita bisa menjalankan perintah 'docker build' di dalam container CircleCI
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build and Push Docker Image
          command: |
            # Mengambil kredensial dari Environment Variables yang disetel di dashboard CircleCI
            echo "$GITHUB_TOKEN" | docker login -u "$GITHUB_USERNAME" --password-stdin
            
            # Memproses build image dengan tag otomatis berdasarkan nomor build CircleCI atau git commit
            IMAGE_NAME="$GITHUB_USERNAME/karsajobs"
            docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$CIRCLE_SHA1 .
            
            # Push Image ke Github Container Registry
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$CIRCLE_SHA1

workflows:
  version: 2
  karsajobs-pipeline:
    jobs:
      - lint-dockerfile:
          filters:
            branches:
              only: karsajobs
      - test-app:
          filters:
            branches:
              only: karsajobs
      # Job build-app hanya akan berjalan jika tahap linting dan testing sudah sukses (requires)
      - build-app-karsajobs:
          requires:
            - lint-dockerfile
            - test-app
          filters:
            branches:
              only: karsajobs